In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#importing the required libraries

In [ ]:
print(np.__version__)
print(pd.__version__)
print(sns.__version__)
#checking the versions of imported libraries

2.0.2
2.2.2
0.13.2

In [ ]:
data = pd.read_csv('/content/dirty_cafe_sales.csv')
#loaded dataset

In [ ]:
data.shape

(10000, 8)

In [ ]:
data.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [ ]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
data.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
data.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
data.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [ ]:
# here we can see the quantity, price per unit, total spent can be float/int & transaction date can be date
data['Quantity'] = pd.to_numeric(data['Quantity'], errors = 'coerce')
data['Price Per Unit'] = pd.to_numeric(data['Price Per Unit'], errors = 'coerce')
data['Total Spent'] = pd.to_numeric(data['Total Spent'], errors = 'coerce')
data['Transaction Date'] = pd.to_datetime(data['Transaction Date'], errors = 'coerce')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 625.1+ KB

In [ ]:
data.describe()

          Quantity  Price Per Unit  Total Spent               Transaction Date
count  9521.000000     9467.000000  9498.000000                           9540
mean      3.028463        2.949984     8.924352  2023-07-01 23:00:31.698113280
min       1.000000        1.000000     1.000000            2023-01-01 00:00:00
25%       2.000000        2.000000     4.000000            2023-04-01 00:00:00
50%       3.000000        3.000000     8.000000            2023-07-02 00:00:00
75%       4.000000        4.000000    12.000000            2023-10-02 00:00:00
max       5.000000        5.000000    25.000000            2023-12-31 00:00:00
std       1.419007        1.278450     6.009919                            NaN

In [ ]:
data.isnull()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,True,False,False
9996,False,True,False,True,False,False,True,False
9997,False,False,False,False,False,False,True,False
9998,False,False,False,True,False,False,True,False
9999,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [ ]:
(data.isnull().sum() / len(data))*100

Transaction ID       0.00
Item                 3.33
Quantity             4.79
Price Per Unit       5.33
Total Spent          5.02
Payment Method      25.79
Location            32.65
Transaction Date     4.60
dtype: float64

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
# we do not have any duplicates in the data, but if we have any duplicates we can remove in this way
data = data.drop_duplicates()

In [ ]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
data.isnull().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [ ]:
data.groupby("Item")["Price Per Unit"].unique()
# this returns unique values in the both the columns

Item
Cake                                 [3.0, nan]
Coffee                               [2.0, nan]
Cookie                               [1.0, nan]
ERROR       [1.5, 3.0, 5.0, nan, 4.0, 2.0, 1.0]
Juice                                [3.0, nan]
Salad                                [5.0, nan]
Sandwich                             [4.0, nan]
Smoothie                             [4.0, nan]
Tea                                  [1.5, nan]
UNKNOWN     [3.0, 1.0, 5.0, 4.0, 1.5, 2.0, nan]
Name: Price Per Unit, dtype: object

In [ ]:
price_map = data.groupby("Item")["Price Per Unit"].mean()
print(price_map)
# in this way we create a price map

Item
Cake        3.000000
Coffee      2.000000
Cookie      1.000000
ERROR       2.944444
Juice       3.000000
Salad       5.000000
Sandwich    4.000000
Smoothie    4.000000
Tea         1.500000
UNKNOWN     2.880368
Name: Price Per Unit, dtype: float64

In [ ]:
data['Price Per Unit'] = data['Price Per Unit'].fillna(data['Item'].map(price_map))

In [ ]:
data.isnull().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit        23
Total Spent          502
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [ ]:
data['Payment Method'] = data['Payment Method'].fillna(data['Payment Method'].mode()[0])

In [ ]:
data.isnull().sum()

Transaction ID         0
Item                 333
Quantity             479
Price Per Unit        23
Total Spent          502
Payment Method         0
Location            3265
Transaction Date     460
dtype: int64

In [ ]:
data['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [ ]:
data["Location"].value_counts(dropna=False)

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [ ]:
loc_map = data.groupby("Payment Method")["Location"].agg(lambda x: x.mode()[0])
print(loc_map)

Payment Method
Cash              In-store
Credit Card       In-store
Digital Wallet    Takeaway
ERROR             In-store
UNKNOWN           Takeaway
Name: Location, dtype: object

In [ ]:

data["Location"] = data["Location"].fillna(data["Payment Method"].map(loc_map))

In [ ]:
data.isnull().sum()

Transaction ID        0
Item                333
Quantity            479
Price Per Unit       23
Total Spent         502
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [ ]:
data.dtypes

Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [ ]:
data["Transaction Date"].value_counts()

Transaction Date
2023-06-16    40
2023-02-06    40
2023-09-21    39
2023-03-13    39
2023-07-24    39
              ..
2023-11-24    15
2023-04-27    15
2023-07-22    14
2023-03-11    14
2023-02-17    14
Name: count, Length: 365, dtype: int64

In [ ]:
data["Transaction Date"].value_counts().sort_index()

Transaction Date
2023-01-01    20
2023-01-02    21
2023-01-03    21
2023-01-04    27
2023-01-05    38
              ..
2023-12-27    24
2023-12-28    21
2023-12-29    25
2023-12-30    27
2023-12-31    20
Name: count, Length: 365, dtype: int64

In [ ]:
data["Transaction Date"].dt.month.value_counts().sort_index()

Transaction Date
1.0     818
2.0     727
3.0     827
4.0     774
5.0     777
6.0     818
7.0     791
8.0     803
9.0     788
10.0    838
11.0    784
12.0    795
Name: count, dtype: int64

In [ ]:
data["Transaction Date"].dt.year.value_counts().sort_index()

Transaction Date
2023.0    9540
Name: count, dtype: int64

In [ ]:
data["Transaction Date"].isnull().sum()

np.int64(460)

In [ ]:
print(data["Transaction Date"].min())
data["Transaction Date"].max()

2023-01-01 00:00:00

Timestamp('2023-12-31 00:00:00')

In [ ]:
data["Transaction Date"].fillna(data["Transaction Date"].mode()[0],inplace=True)

In [ ]:
data.isnull().sum()

Transaction ID        0
Item                333
Quantity            479
Price Per Unit       23
Total Spent         502
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [ ]:
price_map = data.groupby("Item")["Price Per Unit"].median()
print(price_map)

Item
Cake        3.0
Coffee      2.0
Cookie      1.0
ERROR       3.0
Juice       3.0
Salad       5.0
Sandwich    4.0
Smoothie    4.0
Tea         1.5
UNKNOWN     3.0
Name: Price Per Unit, dtype: float64

In [ ]:
reverse_map = (price_map.reset_index().groupby("Price Per Unit")["Item"].first())

print(reverse_map)

Price Per Unit
1.0      Cookie
1.5         Tea
2.0      Coffee
3.0        Cake
4.0    Sandwich
5.0       Salad
Name: Item, dtype: object

In [ ]:
data["Item"] = data["Item"].fillna(data["Price Per Unit"].map(reverse_map))

In [ ]:
data.isnull().sum()

Transaction ID        0
Item                 23
Quantity            479
Price Per Unit       23
Total Spent         502
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [ ]:
data = data.dropna(subset=["Item", "Price Per Unit"])

In [ ]:
data.isnull().sum()

Transaction ID        0
Item                  0
Quantity            478
Price Per Unit        0
Total Spent         501
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [ ]:
data['Total Spent'] = data['Total Spent'].fillna(data['Quantity']*data['Price Per Unit'])

/tmp/ipykernel_3826/3334711354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Total Spent'] = data['Total Spent'].fillna(data['Quantity']*data['Price Per Unit'])

In [ ]:
data.isnull().sum()

Transaction ID        0
Item                  0
Quantity            478
Price Per Unit        0
Total Spent          20
Payment Method        0
Location              0
Transaction Date      0
dtype: int64

In [ ]:
data['Quantity'] = data['Quantity'].fillna(data['Total Spent'] / data['Price Per Unit'])

/tmp/ipykernel_3826/3569177669.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Quantity'] = data['Quantity'].fillna(data['Total Spent'] / data['Price Per Unit'])

In [ ]:
data.isnull().sum()

Transaction ID       0
Item                 0
Quantity            20
Price Per Unit       0
Total Spent         20
Payment Method       0
Location             0
Transaction Date     0
dtype: int64

In [ ]:
data = data.dropna(subset = ['Quantity','Total Spent'])

In [ ]:
data.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [ ]:
data.to_csv('cleaned_dataset.csv', index = False)